<?xml version="1.0" encoding="UTF-8"?>
<definitions name="FTTHSGFTInterface" targetNamespace="http://alsb.telemar/wsdl/WTT/SolicitarAberturaBA" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://alsb.telemar/wsdl/WTT/SolicitarAberturaBA" xmlns:FTTHSGFTInterface="http://alsb.telemar/wsdl/WTT/SolicitarAberturaBA" xmlns:FTTHCommon="FTTHCommon" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="FTTHCommon" schemaLocation="FTTHCommon.xsd"/>
			<import namespace="http://alsb.telemar/wsdl/WTT/SolicitarAberturaBA" schemaLocation="FTTHSGFTInterface.xsd"/>
		</schema>
  </types>
  <message name="acknowledge">
    <part name="acknowledge" element="FTTHCommon:acknowledge">
    </part>
  </message>
  <message name="SolicitarAberturaBAResponseAssincrona">
    <part name="SolicitarAberturaBAResponseAssincrona" type="tns:SolicitarAberturaBAResponseAssincrona">
    </part>
  </message>
  <portType name="AguardarFechamentoBAInterface">
    <operation name="AguardarFechamentoBA">
      <input message="tns:SolicitarAberturaBAResponseAssincrona">
    </input>
      <output message="tns:acknowledge">
    </output>
    </operation>
  </portType>
  <binding name="AguardarFechamentoBASOAP" type="tns:AguardarFechamentoBAInterface">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="AguardarFechamentoBA">
      <soap:operation soapAction="AguardarFechamentoBA"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="AguardarFechamentoBA">
    <port name="AguardarFechamentoBASOAP" binding="tns:AguardarFechamentoBASOAP">
    </port>
  </service>
</definitions>
