<?xml version="1.0" encoding="UTF-8"?>
<definitions name="FTTHServiceRequest" targetNamespace="FTTHServiceRequest" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="FTTHServiceRequest" xmlns:FTTHCommon="FTTHCommon" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:FTTHServiceRequest="FTTHServiceRequest">
  <types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="FTTHCommon" schemaLocation="FTTHCommon.xsd"/>
			<import namespace="FTTHServiceRequest" schemaLocation="FTTHServiceRequest.xsd"/>
		</schema>
  </types>
  <message name="serviceRequest">
    <part name="serviceRequest" element="tns:serviceRequest">
    </part>
  </message>
  <message name="acknowledge">
    <part name="acknowledge" element="FTTHCommon:acknowledge">
    </part>
  </message>
  <portType name="CreateServiceRequestInterface">
    <operation name="CreateServiceRequestOperation">
      <input message="tns:serviceRequest">
    </input>
      <output message="tns:acknowledge">
    </output>
    </operation>
  </portType>
  <binding name="CreateServiceRequestBinding" type="tns:CreateServiceRequestInterface">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="CreateServiceRequestOperation">
      <soap:operation soapAction="CreateServiceRequestOperation"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="CreateServiceRequestService">
    <port name="CreateServiceRequestPort" binding="tns:CreateServiceRequestBinding">
    </port>
  </service>
</definitions>
