<?xml version="1.0" encoding="UTF-8"?>
<WL5G3N0:definitions targetNamespace="http://alsb.telemar/wsdl/WTT/SolicitarAberturaBA" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://alsb.telemar/xsd/WTT/SolicitarAberturaBA" xmlns:WL5G3N2="http://alsb.telemar/xsd/TroubleTicket/SolicitarAberturaBAResponse" xmlns:WL5G3N3="http://alsb.telemar/wsdl/WTT/SolicitarAberturaBA" xmlns:WL5G3N4="http://schemas.xmlsoap.org/wsdl/soap/">
  <WL5G3N0:types>
    <xsd:schema xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://alsb.telemar/wsdl/WTT/SolicitarAberturaBA" xmlns:tnsReq="http://alsb.telemar/xsd/WTT/SolicitarAberturaBA" xmlns:tnsResp="http://alsb.telemar/xsd/TroubleTicket/SolicitarAberturaBAResponse" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://alsb.telemar/xsd/WTT/SolicitarAberturaBA" schemaLocation="SolicitarAberturaBARequest"/>
      <xsd:import namespace="http://alsb.telemar/xsd/TroubleTicket/SolicitarAberturaBAResponse" schemaLocation="SolicitarAberturaBAResponse"/>
    </xsd:schema>
  </WL5G3N0:types>
  <WL5G3N0:message name="SolicitarAberturaBARequest">
    <WL5G3N0:part element="WL5G3N1:SolicitarAberturaBARequest" name="SolicitarAberturaBARequest"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="SolicitarAberturaBAResponse">
    <WL5G3N0:part element="WL5G3N2:SolicitarAberturaBAResponse" name="SolicitarAberturaBAResponse"/>
  </WL5G3N0:message>
  <WL5G3N0:portType name="SolicitarAberturaBA">
    <WL5G3N0:operation name="SolicitarAberturaBA">
      <WL5G3N0:input message="WL5G3N3:SolicitarAberturaBARequest"/>
      <WL5G3N0:output message="WL5G3N3:SolicitarAberturaBAResponse"/>
    </WL5G3N0:operation>
  </WL5G3N0:portType>
  <WL5G3N0:binding name="SolicitarAberturaBASOAP" type="WL5G3N3:SolicitarAberturaBA">
    <WL5G3N4:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <WL5G3N0:operation name="SolicitarAberturaBA">
      <WL5G3N4:operation soapAction="http://alsb.telemar/WTT/SolicitarAberturaBA"/>
      <WL5G3N0:input>
        <WL5G3N4:body use="literal"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N4:body use="literal"/>
      </WL5G3N0:output>
    </WL5G3N0:operation>
  </WL5G3N0:binding>
  <WL5G3N0:service name="SolicitarAberturaBA">
    <WL5G3N0:port binding="WL5G3N3:SolicitarAberturaBASOAP" name="SolicitarAberturaBASOAP">
      <WL5G3N4:address location="http://soahx03:37203/TroubleTicket/SolicitarAberturaBAProxySoap"/>
    </WL5G3N0:port>
  </WL5G3N0:service>
</WL5G3N0:definitions>