<wsdl:definitions name="SolicitarEncerramentoBAFTTHOSB"
	targetNamespace="http://osb.telemar/wsdl/SolicitarEncerramentoBAFTTHOSB/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://osb.telemar/wsdl/SolicitarEncerramentoBAFTTHOSB/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:elem="http://osb.telemar/xsd/ClienteQualidade/SolicitarEncerramentoBAFTTH/V1">

<wsdl:types>
		<xsd:schema>
			<xsd:import
				namespace="http://osb.telemar/xsd/ClienteQualidade/SolicitarEncerramentoBAFTTH/V1"
				schemaLocation="SolicitarEncerramentoBAFTTH.xsd" />
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="SolicitarEncerramentoBAFTTHRequest">
		<wsdl:part name="SolicitarEncerramentoBAFTTHRequest"
			element="elem:SolicitarEncerramentoBAFTTHRequest" />
	</wsdl:message>
	<wsdl:message name="SolicitarEncerramentoBAFTTHResponse">
		<wsdl:part name="SolicitarEncerramentoBAFTTHResponse"
			element="elem:SolicitarEncerramentoBAFTTHResponse" />
	</wsdl:message>

	<wsdl:portType name="SolicitarEncerramentoBAFTTHOSB">
		<wsdl:operation name="SolicitarEncerramentoBAFTTH">
			<wsdl:input message="tns:SolicitarEncerramentoBAFTTHRequest" />
			<wsdl:output message="tns:SolicitarEncerramentoBAFTTHResponse" />
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="SolicitarEncerramentoBAFTTHOSBSoap"
		type="tns:SolicitarEncerramentoBAFTTHOSB">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="SolicitarEncerramentoBAFTTH">
			<soap:operation soapAction="http://osb.telemar/wsdl/SolicitarEncerramentoBAFTTH" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="SolicitarEncerramentoBAFTTH">
		<wsdl:port binding="tns:SolicitarEncerramentoBAFTTHOSBSoap"
			name="SolicitarEncerramentoBAFTTHOSBSoap">
			<soap:address location="http://server:port/service" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>