<?xml version="1.0" encoding="UTF-8"?>
<WL5G3N0:definitions targetNamespace="http://alsb.telemar/wsdl/SolicitarEncerramentoExterno" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://alsb.telemar/xsd/ESB/SolicitarEncerramentoExterno" xmlns:WL5G3N2="http://alsb.telemar/xsd/ESB/SolicitarEncerramentoExternoResponse" xmlns:WL5G3N3="http://alsb.telemar/wsdl/SolicitarEncerramentoExterno" xmlns:WL5G3N4="http://schemas.xmlsoap.org/wsdl/soap/">
  <WL5G3N0:types>
    <xsd:schema xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://alsb.telemar/wsdl/SolicitarEncerramentoExterno" xmlns:tnsReq="http://alsb.telemar/xsd/ESB/SolicitarEncerramentoExterno" xmlns:tnsResp="http://alsb.telemar/xsd/ESB/SolicitarEncerramentoExternoResponse" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://alsb.telemar/xsd/ESB/SolicitarEncerramentoExterno" schemaLocation="SolicitarEncerramentoExternoProxySoap.xsd"/>
      <xsd:import namespace="http://alsb.telemar/xsd/ESB/SolicitarEncerramentoExternoResponse" schemaLocation="SolicitarEncerramentoExternoProxySoap_1_2.xsd"/>
    </xsd:schema>
  </WL5G3N0:types>
  <WL5G3N0:message name="SolicitarEncerramentoExternoRequest">
    <WL5G3N0:part element="WL5G3N1:SolicitarEncerramentoExternoRequest" name="SolicitarEncerramentoExternoRequest"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="SolicitarEncerramentoExternoResponse">
    <WL5G3N0:part element="WL5G3N2:SolicitarEncerramentoExternoResponse" name="SolicitarEncerramentoExternoResponse"/>
  </WL5G3N0:message>
  <WL5G3N0:portType name="SolicitarEncerramentoExterno">
    <WL5G3N0:operation name="SolicitarEncerramentoExterno">
      <WL5G3N0:input message="WL5G3N3:SolicitarEncerramentoExternoRequest"/>
      <WL5G3N0:output message="WL5G3N3:SolicitarEncerramentoExternoResponse"/>
    </WL5G3N0:operation>
  </WL5G3N0:portType>
  <WL5G3N0:binding name="SolicitarEncerramentoExternoSOAP" type="WL5G3N3:SolicitarEncerramentoExterno">
    <WL5G3N4:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <WL5G3N0:operation name="SolicitarEncerramentoExterno">
      <WL5G3N4:operation soapAction="http://alsb.telemar/TroubleTicket/SolicitarEncerramentoExterno"/>
      <WL5G3N0:input>
        <WL5G3N4:body use="literal"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N4:body use="literal"/>
      </WL5G3N0:output>
    </WL5G3N0:operation>
  </WL5G3N0:binding>
  <WL5G3N0:service name="SolicitarEncerramentoExternoSOAPQSService">
    <WL5G3N0:port binding="WL5G3N3:SolicitarEncerramentoExternoSOAP" name="SolicitarEncerramentoExternoSOAPQSPort">
      <WL5G3N4:address location="http://soapx58a:7205/TroubleTicket/SolicitarEncerramentoExternoProxySoap"/>
    </WL5G3N0:port>
  </WL5G3N0:service>
</WL5G3N0:definitions>